"""empty message

Revision ID: 3c4187f3693d
Revises: 961e7170860c
Create Date: 2025-07-24 17:52:02.386137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4187f3693d'
down_revision = '961e7170860c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pinneds',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'user_id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('set_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('urgent', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('tasks_task_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_unique_constraint('tasks_task_key', ['task'])
        batch_op.drop_column('urgent')
        batch_op.drop_column('location')
        batch_op.drop_column('set_time')
        batch_op.drop_column('set_date')

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.drop_table('Pinneds')
    # ### end Alembic commands ###
