"""empty message

Revision ID: c4c2f0bbad8c
Revises: 3c4187f3693d
Create Date: 2025-07-24 19:55:43.844685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4c2f0bbad8c'
down_revision = '3c4187f3693d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('schedule_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('set_time')
        batch_op.drop_column('set_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('set_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('reminder_at')
        batch_op.drop_column('schedule_at')
        batch_op.drop_column('due_at')

    # ### end Alembic commands ###
